### PR TITLE
Adaptation to ROS indigo (building as ros package).

### PR DESCRIPTION
**Pull request by danioto**
Hello!

I needed to use a clever depth calibration in my Xtion cameras and found your paper and repository. Compiling up-to-date version didn't not allow to use it as ros package. There is also some changes to get rid of all warnings during compilation.

How do you think? :smile: 

Regards,
Daniel

### CODE REVIEW

**Comment by mauriliodc** [comment]
Hi Daniel!
Thank you for your interest.
Did you have good result?

I wanna check a couple of thing before merge everything together. Basically i forgot to push an updated version from the last publication (i'm not sure which part i did not push but basically it should be far more accurate and include a new unbiasing method to recover the systematic error).

Best,
Maurilio

**Comment by mauriliodc** [comment]
it seems it pushed the last version cool :dancer:

**Comment by danioto** [comment]
Maurilio,

I must admit I do not have the opportunity to check the performance yet. So far I was implementing the bounding box that allow me to use LUT generated with your package in my project. Tomorow I will still work on it and maybe could say more.

As far as you push updates I will pull it and test on my workspace :smile:

Thanks for fast replay!
Daniel

**Comment by mauriliodc** [comment]
Can i ask you why do you need a bounding box? What is your project? As long as you can talk about it, I'd like to know, curiosity sake, nothing more :D

**Comment by danioto** [comment]
Maurilio,

main target is to use two Xtion cameras as obstacle sensors for mobile robot. As far as first is working with simple depth-based algorithm, the second one has pretty advanced information processing path - with normal vector and inclination calculation etc. The problem is the sphere distortion of Xtion's and that is why I need your package.

As bounding box I meant my own class that could read LUT from file. It is necessary because I have strong time restriction and everything is processed in parallel with CUDA technology. Your code is clean and easy to understand and I just cut some pieces and put them into my project (calibrationMatrix class).

Thank you very much for this package - it saved a lot of my time. I would be glad to help you with tests or something like that. Will be in touch!

Daniel

**Pull request merged**
